import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const foundersRegular = localFont({
  src: "./fonts/FoundersRegular.otf",
  variable: "--font-founders-regular",
  display: "swap",
});

const foundersBold = localFont({
  src: "./fonts/FoundersBold.otf",
  variable: "--font-founders-bold",
  display: "swap",
});

const pressStart2P = Press_Start_2P({
  weight: "400",
  variable: "--font-press-start-2p",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${foundersRegular.variable} ${foundersBold.variable} ${pressStart2P.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
