import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const foundersRegular = localFont({
  src: "./fonts/FoundersRegular.otf",
  variable: "--font-founders-regular",
  display: "swap",
});

const foundersBold = localFont({
  src: "./fonts/FoundersBold.otf",
  variable: "--font-founders-bold",
  display: "swap",
});

const consolas = localFont({
  src: "./fonts/consolas.ttf",
  variable: "--font-consolas-regular",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${foundersRegular.variable} ${foundersBold.variable} ${consolas.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
